### PR TITLE
Added Unicode/Zawgyi Option

### PR DESCRIPTION
**Pull request by setkyar**

### CODE REVIEW

**Comment by setkyar** [comment]
@swanhtet1992 , I try to remove `Uncaught TypeError: Cannot read property 'appendChild' of null` error on other's site console.

I try to work it on facebook :smile: Added new one :+1:

**Comment by swanhtet1992** [comment]
Great!! :+1:

I'll look on to this and will merge with #1 together.

**Comment by swanhtet1992** [comment]
@setkyar meanwhile could you please check issue #3 ?

**Comment by setkyar** [comment]
Added Document Ready State & Stop Working on empty status. And fixed issue [#3](https://github.com/swanhtet1992/MagicButton/issues/3)! :tada:

**Pull request merged**
